### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by AllinolCP** [takahatashun/osu-beatmapset-downloader#1]
log
```
Error: 403 Forbidden
    at advancedLogin (E:\Dance-Contest-Plus\server\node_modules\osu-beatmapset-downloader\dist\util\OsuUtil.js:11:15)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async login (E:\Dance-Contest-Plus\server\node_modules\osu-beatmapset-downloader\dist\util\OsuUtil.js:34:13)
    at async downloadFile (E:\Dance-Contest-Plus\server\downloader.js:188:16)
    at async E:\Dance-Contest-Plus\server\index.js:19:31
```

**Comment by K4zoku** [comment]
~~try login with cookie instead~~
**#EDIT:** I have tested again, the problem didn't appear, maybe your login infomation is wrong, check it and try again!!

**Comment by K4zoku** [comment]
4 days with no response, close issue.
If you are still having this issue, please open new issue.

**Comment by AllinolCP** [comment]
it turns out to be my ip address that was having a bad score with cloudflare
